export const WS_NEW_CREATING        = 'WS_NEW_CREATING'
export const WS_ONOPEN              = 'WS_ONOPEN'
export const WS_ONCLOSE             = 'WS_ONCLOSE'
export const WS_ONERROR             = 'WS_ONERROR'
export const WS_ONMESSAGE           = 'WS_ONMESSAGE'