---
swagger: "2.0"

################################################################################
#                              API Information                                 #
################################################################################
info:
  version: "1.0.0"
  title: "Asterisk stasis REACTOR"
  description: |
    Обеспечивает работу [React-component](http://192.168.13.97:8005)
    Открыт для Websocket ws://192.168.13.97:8006

    Общается с Asterisk ARI: openapi spec - http://192.168.16.14:8088/ari/api-docs/resources.json
    Общается с MySQL: 192.168.26.17

################################################################################
#                  Host, Base Path, Schemes and Content Types                  #
################################################################################
host: '192.168.13.97:8004'
basePath: /v2api
schemes:
  - http
produces:
  - application/json
consumes:
  - application/json

################################################################################
#                                   Tags                                       #
################################################################################
tags:
  - name: Configuration
    description: Конфигурация PBX
  - name: pbx
    description: Состояние PBX
  - name: Data
    description: Smart данные всякие
  - name: callPlatform
    description: Тестовый "Колл-Центр" на базе PBX

################################################################################
#                                    Paths                                     #
################################################################################
paths:

  /endpoint:
    get:
      tags:
        - Configuration
      description: endpoints list
      operationId: endpoint_get
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - name: token
          in: header
          description: token
          required: true
          type: string
        - name: name
          in: query
          description: endpoint name
          required: false
          type: string
        - name: group
          in: query
          description: endpoint group id
          required: false
          type: string
      responses:
        '200':
          description: endpoint list
          schema:
            type: array
            items:
              $ref: '#/definitions/endpoint_getlist'
        '202':
          description: no list
          schema:
            $ref: '#/definitions/dummy'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
      x-swagger-router-controller: Configuration
    post:
      tags:
        - Configuration
      description: endpoint add 
      operationId: endpoint_post
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - name: token
          in: header
          description: token
          required: true
          type: string
        - name: body
          in: body
          description: |
            В zabbix-reactor написана логика добавления хоста в Zabbix на базе двух параметров dns-адреса хоста и groupid.
            Можно накрутить любую логику по своему желанию. См. controller "config_endpoint_post.js".
          required: true
          schema:
            $ref: '#/definitions/endpoint_add'
      responses:
        '200':
          description: endpoint created
          schema:
            $ref: '#/definitions/dummy'
        '202':
          description: endpoint not created
          schema:
            $ref: '#/definitions/dummy'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
      x-swagger-router-controller: Configuration
    put:
      tags:
        - Configuration
      description: endpoint update
      operationId: endpoint_put
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - name: token
          in: header
          description: token
          required: true
          type: string
        - name: endpointid
          in: query
          description: endpoint id
          required: true
          type: string
        - name: body
          in: body
          description: endpoint name
          required: true
          schema:
            $ref: '#/definitions/endpoint_update'
      responses:
        '200':
          description: endpoint updated
          schema:
            $ref: '#/definitions/dummy'
        '202':
          description: endpoint not updated
          schema:
            $ref: '#/definitions/dummy'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
      x-swagger-router-controller: Configuration
    delete:
      tags:
        - Configuration
      description: endpoint delete
      operationId: endpoint_del
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - name: token
          in: header
          description: token
          required: true
          type: string
        - name: endpointid
          in: query
          description: endpoint id
          required: true
          type: string
      responses:
        '200':
          description: endpoint deleted
          schema:
            $ref: '#/definitions/dummy'
        '202':
          description: endpoint not deleted
          schema:
            $ref: '#/definitions/dummy'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
      x-swagger-router-controller: Configuration

  /channelsState:
    get:
      tags:
      - "pbx"
      description: "Выводит активные каналы"
      operationId: "channels_state"
      produces:
      - "application/json"
      parameters:
      - name: token
        in: header
        description: token
        required: true
        type: string
      - name: "direction"
        in: "query"
        description: "Направление вызова (in/out)"
        required: false
        type: "string"
      responses:
        200:
          description: "активные каналы"
          schema:
            $ref: "#/definitions/channels_state"
        202:
          description: "пусто"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/dummy"
        default:
          description: "unexpected error"
          schema:
            $ref: "#/definitions/errorModel"
      x-swagger-router-controller: "Pbx"
    x-swagger-router-controller: "Pbx"
  /callPlatform/originateList:
    post:
      tags:
      - "callPlatform"
      description: |
        Делаем набор с кучи endpoint на кучу exten
        ```json
        {
           "endpoint": [
              "PJSIP/509"
            ],
            "exten": [
              "74957856400",
              "74957856400"
            ]
        }
        ```
      operationId: "originateCallList"
      produces:
      - "application/json"
      parameters:
      - name: token
        in: header
        description: token
        required: true
        type: string
      - name: "originateParam"
        in: "body"
        description: "JSON объект содержащий [массив-endpoint], context, [массив-exten]"
        required: true
        schema:
          $ref: "#/definitions/inOriginateListObj"
      responses:
        200:
          description: "Статус операции"
          schema:
            $ref: "#/definitions/statusPost"
        default:
          description: "unexpected error"
          schema:
            $ref: "#/definitions/errorModel"
      x-swagger-router-controller: "CallPlatform"
    x-swagger-router-controller: "CallPlatform"

  /chanlink:
    get:
      tags:
        - Data
      description: channels links Object
      operationId: chanlink_get
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - name: token
          in: header
          description: token
          required: true
          type: string
        - name: layer
          in: query
          description: на каком уровне линки L1, L2, L3
          required: true
          type: string
      responses:
        '200':
          description: chanlinks
          schema:
            $ref: '#/definitions/chanlinks'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
      x-swagger-router-controller: Data
      
    x-swagger-router-controller: Data
################################################################################
#                                 Definitions                                  #
################################################################################
definitions:

# endpoint_add ------------------------------------------------------------------------
  endpoint_add:
    type: object
    properties:
      dns:
        type: string
      groupid:
        type: integer

# endpoint_update ------------------------------------------------------------------------
  endpoint_update:
    type: object
    properties:
      description:
        type: string
      inventory:
        type: object
        properties:
          notes:
            type: string

# endpoint_list -------------------------------------------------------------------
  endpoint_getlist:
    type: object
    properties:
      technology:
        type: string
      resource:
        type: string
      state:
        type: string
      channel_ids:
        type: array
        items:
          type: string

  inOriginateListObj:
    type: "object"
    required:
    - "endpoint"
    - "exten"
    properties:
      endpoint:
        type: "array"
        items:
          type: "string"
      exten:
        type: "array"
        items:
          type: "string"
  channels:
    type: "object"
    properties:
      id:
        type: "string"
      name:
        type: "string"
      state:
        type: "string"
      caller_number:
        type: "string"
      dialplan_exten:
        type: "string"
  statusPost:
    type: "object"
    properties:
      status:
        type: "string"

  channels_state:
    type: "object"
    properties:
      channels:
        type: "array"
        items:
          type: "object"
          properties:
            id:
              type: "string"
            name:
              type: "string"
            state:
              type: "string"
            creationtime:
              type: "string"
            dialplan_context:
              type: "string"
            dialplan_exten:
              type: "string"
            caller_number:
              type: "string"
      bridges:
        type: "array"
        items:
          type: "object"
          properties:
            id:
              type: "string"
            channels:
              type: "array"
              items:
                type: "string"

# chanlinks -------------------------------------------------------------------
  chanlinks:
    type: object
    properties:
      nodes:
        type: array
        items:
          type: object
          properties:
            id:
              type: string
            group:
              type: string
            idChannel:
              type: string
            size:
              type: integer
      links:
        type: array
        items:
          type: object
          properties:
            source:
              type: string
            target:
              type: string
            value:
              type: integer

  dummy:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      message:
        type: "string"
  errorModel:
    type: "object"
    required:
    - "code"
    - "message"
    properties:
      code:
        type: "integer"
        format: "int32"
      message:
        type: "string"
