---
swagger: "2.0"

################################################################################
#                              API Information                                 #
################################################################################
info:
  version: "1.0.3"
  title: "call platform api"
  description: |
    openapi-2.0 спецификация:
    http://asterisk-test.intellin-tech.ru:8080/api-docs
    
    Общается с API Asterisk. openapi-1.1 спецификация:
    http://asterisk-test.intellin-tech.ru:8088/ari/api-docs/resources.json
    
    ## callPlatform
    Эта фигня запускает автоматический обзвон, АКА Колл-Центр

    ## PBX
    Тут можно поработать PBX-функционалом платформы

    ## Websocket Server
    Снабдил API своим Websocket сервером. Работает на порту 8001. 
    Послушать события можно на [vrf](http://vrf.intellin-tech.ru/aster_test.html).

################################################################################
#                  Host, Base Path, Schemes and Content Types                  #
################################################################################
host: 'localhost:8004'
basePath: /v2api
schemes:
  - http
produces:
  - application/json
consumes:
  - application/json

################################################################################
#                                   Tags                                       #
################################################################################
tags:
  - name: callPlatform
    description: "Колл-Центр"
  - name: pbx
    description: "Мини-АТС"

################################################################################
#                                    Paths                                     #
################################################################################
paths:
  /pbx/channelsState:
    get:
      tags:
      - "pbx"
      description: "Выводит активные каналы"
      operationId: "channelsState"
      produces:
      - "application/json"
      parameters:
      - name: "direction"
        in: "query"
        description: "Направление вызова (in/out)"
        required: false
        type: "string"
      responses:
        200:
          description: "распечатка активных каналов"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/channels"
        default:
          description: "unexpected error"
          schema:
            $ref: "#/definitions/errorModel"
      x-swagger-router-controller: "Pbx"
    x-swagger-router-controller: "Pbx"
  /callPlatform/originateList:
    post:
      tags:
      - "callPlatform"
      description: |
        Делаем набор с кучи endpoint на кучу exten
        ```json
        {
           "endpoint": [
              "PJSIP/509"
            ],
            "exten": [
              "74957856400",
              "74957856400"
            ]
        }
        ```
      operationId: "originateCallList"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "originateParam"
        description: "JSON объект содержащий [массив-endpoint], context, [массив-exten]"
        required: true
        schema:
          $ref: "#/definitions/inOriginateListObj"
      responses:
        200:
          description: "Статус операции"
          schema:
            $ref: "#/definitions/statusPost"
        default:
          description: "unexpected error"
          schema:
            $ref: "#/definitions/errorModel"
      x-swagger-router-controller: "CallPlatform"
    x-swagger-router-controller: "CallPlatform"

################################################################################
#                                 Definitions                                  #
################################################################################
definitions:
  inOriginateListObj:
    type: "object"
    required:
    - "endpoint"
    - "exten"
    properties:
      endpoint:
        type: "array"
        items:
          type: "string"
      exten:
        type: "array"
        items:
          type: "string"
  channels:
    type: "object"
    properties:
      id:
        type: "string"
      name:
        type: "string"
      state:
        type: "string"
      caller_number:
        type: "string"
      dialplan_exten:
        type: "string"
  statusPost:
    type: "object"
    properties:
      status:
        type: "string"
  errorModel:
    type: "object"
    required:
    - "code"
    - "message"
    properties:
      code:
        type: "integer"
        format: "int32"
      message:
        type: "string"
