---
swagger: "2.0"

################################################################################
#                              API Information                                 #
################################################################################
info:
  version: "1.0.0"
  title: "Asterisk stasis REACTOR"
  description: |
    Обеспечивает работу [React-component](http://192.168.13.97:8005)
    Открыт для Websocket ws://192.168.13.97:8006

    Общается с Asterisk ARI: openapi spec - http://192.168.16.14:8088/ari/api-docs/resources.json
    Общается с MySQL: 192.168.26.17

################################################################################
#                  Host, Base Path, Schemes and Content Types                  #
################################################################################
host: '192.168.13.97:8004'
basePath: /v2api
schemes:
  - http
produces:
  - application/json
consumes:
  - application/json

################################################################################
#                                   Tags                                       #
################################################################################
tags:
  - name: pbx
    description: "Мини-АТС"
  - name: callPlatform
    description: "Колл-Центр"

################################################################################
#                                    Paths                                     #
################################################################################
paths:
  /pbx/channelsState:
    get:
      tags:
      - "pbx"
      description: "Выводит активные каналы"
      operationId: "channels_state"
      produces:
      - "application/json"
      parameters:
      - name: token
        in: header
        description: token
        required: true
        type: string
      - name: "direction"
        in: "query"
        description: "Направление вызова (in/out)"
        required: false
        type: "string"
      responses:
        200:
          description: "активные каналы"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/platform_channels"
        202:
          description: "пусто"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/dummy"
        default:
          description: "unexpected error"
          schema:
            $ref: "#/definitions/errorModel"
      x-swagger-router-controller: "Pbx"
    x-swagger-router-controller: "Pbx"
  /callPlatform/originateList:
    post:
      tags:
      - "callPlatform"
      description: |
        Делаем набор с кучи endpoint на кучу exten
        ```json
        {
           "endpoint": [
              "PJSIP/509"
            ],
            "exten": [
              "74957856400",
              "74957856400"
            ]
        }
        ```
      operationId: "originateCallList"
      produces:
      - "application/json"
      parameters:
      - name: token
        in: header
        description: token
        required: true
        type: string
      - name: "originateParam"
        in: "body"
        description: "JSON объект содержащий [массив-endpoint], context, [массив-exten]"
        required: true
        schema:
          $ref: "#/definitions/inOriginateListObj"
      responses:
        200:
          description: "Статус операции"
          schema:
            $ref: "#/definitions/statusPost"
        default:
          description: "unexpected error"
          schema:
            $ref: "#/definitions/errorModel"
      x-swagger-router-controller: "CallPlatform"
    x-swagger-router-controller: "CallPlatform"

################################################################################
#                                 Definitions                                  #
################################################################################
definitions:
  inOriginateListObj:
    type: "object"
    required:
    - "endpoint"
    - "exten"
    properties:
      endpoint:
        type: "array"
        items:
          type: "string"
      exten:
        type: "array"
        items:
          type: "string"
  channels:
    type: "object"
    properties:
      id:
        type: "string"
      name:
        type: "string"
      state:
        type: "string"
      caller_number:
        type: "string"
      dialplan_exten:
        type: "string"
  statusPost:
    type: "object"
    properties:
      status:
        type: "string"
  platform_channels:
    type: "object"
    properties:
      sip_tg:
        type: "string"
      application:
        type: "string"
      context:
        type: "string"
      extension:
        type: "string"
      channelstatedesc:
        type: "string"
      calleridnum:
        type: "string"
      connectedlinenum:
        type: "string"
      duration:
        type: "string"
      b_sip_tg:
        type: "string"
      b_application:
        type: "string"
      b_context:
        type: "string"
      b_extension:
        type: "string"
      b_channelstatedesc:
        type: "string"
      b_calleridnum:
        type: "string"
      b_connectedlinenum:
        type: "string"
      b_duration:
        type: "string"
      call_direction:
        type: "string"
  dummy:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      message:
        type: "string"
  errorModel:
    type: "object"
    required:
    - "code"
    - "message"
    properties:
      code:
        type: "integer"
        format: "int32"
      message:
        type: "string"
